"""ledgerly v2 tables

Revision ID: e16be2e98ba0
Revises: 
Create Date: 2026-06-29 22:17:52.809152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e16be2e98ba0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('ai_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ai_action', sa.String(length=100), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_logs_id'), 'ai_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_logs_invoice_id'), 'ai_logs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_user_id'), 'ai_logs', ['user_id'], unique=False)
    op.create_table('invoice_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_documents_id'), 'invoice_documents', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_documents_invoice_id'), 'invoice_documents', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.add_column('clients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("""
    UPDATE clients
    SET user_id = (SELECT id FROM users LIMIT 1)
    WHERE user_id IS NULL
""")
    op.alter_column(
    'clients',
    'user_id',
    nullable=False
)
    op.add_column('clients', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('payment_behavior', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('extensions', sa.Column('requested_days', sa.Integer(), nullable=False))
    op.add_column('extensions', sa.Column('old_due_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('extensions', sa.Column('ai_generated_message', sa.Text(), nullable=True))
    op.add_column('extensions', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_extensions_invoice_id'), 'extensions', ['invoice_id'], unique=False)
    op.drop_constraint(op.f('extensions_invoice_id_fkey'), 'extensions', type_='foreignkey')
    op.create_foreign_key(None, 'extensions', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'extensions', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_column('extensions', 'days_extended')
    op.drop_column('extensions', 'ai_message')
    op.drop_column('extensions', 'original_due_date')
    op.add_column('invoices', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('issue_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('invoices', sa.Column('ai_analysis', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.drop_constraint(op.f('invoices_client_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoices', 'issued_date')
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'role')
    op.add_column('invoices', sa.Column('issued_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_client_id_fkey'), 'invoices', 'clients', ['client_id'], ['id'])
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.alter_column('invoices', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('invoices', 'updated_at')
    op.drop_column('invoices', 'ai_analysis')
    op.drop_column('invoices', 'issue_date')
    op.drop_column('invoices', 'tax')
    op.drop_column('invoices', 'user_id')
    op.add_column('extensions', sa.Column('original_due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('extensions', sa.Column('ai_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('extensions', sa.Column('days_extended', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'extensions', type_='foreignkey')
    op.drop_constraint(None, 'extensions', type_='foreignkey')
    op.create_foreign_key(op.f('extensions_invoice_id_fkey'), 'extensions', 'invoices', ['invoice_id'], ['id'])
    op.drop_index(op.f('ix_extensions_invoice_id'), table_name='extensions')
    op.drop_column('extensions', 'approved_by')
    op.drop_column('extensions', 'ai_generated_message')
    op.drop_column('extensions', 'old_due_date')
    op.drop_column('extensions', 'requested_days')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'payment_behavior')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'user_id')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoice_documents_invoice_id'), table_name='invoice_documents')
    op.drop_index(op.f('ix_invoice_documents_id'), table_name='invoice_documents')
    op.drop_table('invoice_documents')
    op.drop_index(op.f('ix_ai_logs_user_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_invoice_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_id'), table_name='ai_logs')
    op.drop_table('ai_logs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
